### ISSUE TITLE
Caching plugin not working with content-encoding gzip

### ISSUE THREAD

**Issue by srilathatata** [wshirey/kong-plugin-response-cache#7]
Hi
This is a nice plugin , works perfectly for JSON content encoding, but I am trying to configure this for content-encoding as gizp, empty body is shown, any help appreciated,thanks

**Comment by wshirey** [comment]
Hi @srilathatata, that's probably something I won't add, but will definitely update the docs to specify it only handles JSON content. If you wanted to fork and modify on your own, you'll need to modify the following lines to handle your gzip data: https://github.com/wshirey/kong-plugin-response-cache/blob/master/handler.lua#L175-L180
